# SPDX-License-Identifier: PMPL-1.0-or-later
name: CI

permissions: read-all

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.9', '1.10', '1.11', 'nightly']
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@a0a0978e4ec4b89e96c418be701e7d94bc0c62fc # v2.3.0
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}

      - name: Cache Julia artifacts
        uses: julia-actions/cache@580d2b69d895343992af2cbad49c32a2b8325da0 # v2.0.1

      - name: Build package
        uses: julia-actions/julia-buildpkg@90dd6f23eb49626e4e6612cb9d64d456f86e6a1c # v1.6.0

      - name: Run tests
        uses: julia-actions/julia-runtest@79a7e100883947123f8263c5f06e6c2fee60dd0c # v1.10.0

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@03114f09f119417c3242a9fb6e0b722676aedf38 # v1.2.2

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.2.1
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
