name = "Exnovation"
uuid = "eb535ea2-a284-4d5f-a499-9e884733dc08"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]
version = "1.0.1"
license = "PMPL-1.0-or-later"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
julia = "1.9"
JSON3 = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
