[deps]
Cliodynamics = "8d2f3e70-4c6b-5e9c-a3d1-2f8e9c0b1d2e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[sources]
Cliodynamics = {path = ".."}

[compat]
Documenter = "1"
