name = "ShellIntegration"
uuid = "c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"
authors = ["Hyperpolymath <jonathan.jewell@open.ac.uk>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c9795de"

[compat]
julia = "1.10"
