name = "Lithoglyph"
uuid = "f1e2d3c4-b5a6-4b7c-8d9e-0f1a2b3c4d5e"
authors = ["Hyperpolymath <jonathan.jewell@open.ac.uk>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f5b860d-d184-4516-a1c6-1744e9610e04"
Libdl = "8f399da3-3557-5675-b5ff-fb832c9795de"

[compat]
julia = "1.10"
