name = "BowtieRisk"
uuid = "f4857c2c-646e-44f8-8901-46c9ace85fa6"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]
version = "1.0.0"
license = "PMPL-1.0-or-later"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
julia = "1.9"
JSON3 = "1"
Distributions = "0.25"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
