name = "TradeUnionist"
uuid = "c3d4e5f6-7g8h-9i0j-k1l2-m3n4o5p6q7r8"
authors = ["Hyperpolymath <jonathan.jewell@open.ac.uk>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSON3 = "0f5b860d-d184-4516-a1c6-1744e9610e04"
SQLite = "0aa819cd-06f1-547f-88ef-0d1bc55bc9b6"
Dates = "ade2ca70-3891-5945-931b-dc5ea821e773"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
LibGEOS = "d921b63e-47ff-5d4a-934a-e24339b2057b"
GeoInterface = "cf35f861-3891-596d-8f2e-e2afcf0c11f7"
DuckDB = "ce010024-2d86-4e57-9d7d-f65a8aedab41"
PRComms = "b2c3d4e5-6f7g-8h9i-0j1k-l2m3n4o5p6q7"
BowtieRisk = "d5e6f7g8-9h0i-1j2k-l3m4-n5o6p7q8r9s0"
Exnovation = "e6f7g8h9-0i1j-2k3l-m4n5-o6p7q8r9s0t1"

[compat]
julia = "1.10"
