# SPDX-License-Identifier: PMPL-1.0-or-later
name = "SMTLib"
uuid = "7d3f9a2c-8b4e-5c1f-a6d0-9e8f7b2c3d4e"
authors = ["Jonathan D.A. Jewell <jonathan.jewell@open.ac.uk>"]
version = "0.1.1"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
