name = "MinixSDK"
uuid = "d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"
authors = ["Hyperpolymath <jonathan.jewell@open.ac.uk>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c9795de"

[compat]
julia = "1.10"
